#!/usr/bin/env php
<?php

namespace Major\OkoPrss;

use NunoMaduro\Collision\Provider as Collision;
use Psl\Dict;
use Psl\File;
use Psl\Vec;

require_once __DIR__ . '/vendor/autoload.php';

(new Collision())->register();

$articles = Vec\map_with_key(
    require __DIR__ . '/urls.php',
    fn (int $n, string $a) => get_source($n, $a),
);

$entries = Vec\flat_map($articles, fn (string $a) => parse_entries($a));

$feed = generate_atom(Dict\take($entries, 250));
$full = generate_atom($entries);

File\write(__DIR__ . '/feed/atom.xml', $feed, File\WriteMode::TRUNCATE);
File\write(__DIR__ . '/feed/full.xml', $full, File\WriteMode::TRUNCATE);
