<?php

return [
    44 => 'wojna-ukraina-44-dzien',
    43 => 'putin-chce-zakonczyc-wojne-do-9-maja-zelenski-rosja-tuszuje-zbrodnie-w-mariupolu-dzien-43-na-zywo',
    42 => 'wybuchy-obok-lwowa-i-dniepru-usa-szykuja-nowe-sankcje-wobec-rosji-dzien-42-na-zywo',
    41 => 'zelenski-do-rosyjskich-wojskowych-wasze-zycie-skonczy-sie-za-kratkami-dzien-41-na-zywo',
    40 => 'zelenski-o-rosyjskich-zolnierzach-rzeznicy-mordercy-gwalciciele-odessa-pod-ostrzalemdzien-40-na-zywo',
    39 => 'silne-eksplozje-rosja-atakuje-z-powietrza-odesse-dzien-39-na-zywo',
    38 => 'zelenski-ostrzega-przed-wspolpraca-z-rosjanami-gauleiterzy-moga-sie-meldowac-w-rostowie-dzien-38-na-zywo',
    37 => 'ewakuacja-zniszczonego-mariupola-ukrainskie-wojsko-robi-postepy-pod-czernihowem-dzien-37-na-zywo',
    36 => 'rosja-przygotowuje-wielka-ofensywe-w-donbasie-twierdzi-zelenski-dzien-36-na-zywo',
    35 => 'swiat-nie-wierzy-w-wycofywanie-sie-rosjan-dzien-35-na-zywo',
    34 => 'kolejna-runda-negocjacji-w-turcji-centrum-mariupola-wciaz-pod-kontrola-ukrainy-dzien-34-na-zywo',
    33 => 'podolak-rosja-nie-ma-juz-jezyka-humanizmu-tylko-bomby-i-proby-zmiecenia-ukrainy-dzien-33-na-zywo',
    32 => 'zelenski-prosi-zachod-o-dostawy-ciezkiej-broni-nie-stracimy-rakiet-strzelbami-dzien-32-na-zywo',
    31 => 'biden-spotka-sie-w-polsce-z-ukrainskimi-ministrami-dzien-31-na-zywo',
    30 => 'do-polski-przylatuje-joe-biden-ukraina-zada-uwolnienia-uprowadzonych-samorzadowcow-dzien-30-na-zywo',
    29 => 'miesiac-od-wybuchu-wojny-zelenski-wzywa-wyjdzcie-na-ulice-okazcie-wsparcie-ukrainie-dzien-29-na-zywo',
    28 => 'ukraina-wojna-dzien-28-na-zywo',
    27 => 'ukraina-odrzucila-rosyjskie-ultimatum-w-sprawie-mariupola-dzien-27-na-zywo',
    26 => 'dzis-piata-runda-rozmow-ukrainy-i-rosji-mariupol-okrazony-rosjanie-stawiaja-ultimatium-dzien-26-wojny-na-zywo',
    25 => '130-zolnierzy-z-jednej-dywizji-odmowilo-udzialu-w-wojnie-rosja-wprowadzi-mobilizacjedzien-25-na-zywo',
    24 => 'zelenski-czas-na-spotkanie-nie-zyje-rosyjski-general-mordwiczew-dzien-24-na-zywo',
    23 => 'eksplozje-lwow-ukraina-23-dzien',
    22 => 'zelenski-rosja-stala-sie-panstwem-terrorystycznym-ukraina-dzien-22-na-zywo',
    21 => 'alarmy-bombowe-w-kijowie-jaroslaw-kaczynski-zaapelowal-o-pokojowa-misje-nato-ukraina-dzien-21-na-zywo',
    20 => 'zelenski-do-rosyjskich-zolnierzy-dlaczego-musicie-umierac-chcecie-zyc-wiemy-to-ukraina-dzien-20-na-zywo',
    19 => 'zmarla-ciezarna-ze-slynnego-zdjecia-ze-szpitala-w-mariupolu-kolejna-runda-negocjacji-pokojowychukraina-dzien-19-na-zywo',
    16 => 'rosja-sie-okopuje-i-sieje-smierc-ukraina-dzien-16-na-zywo',
    15 => 'rosja-dalej-atakuje-charkow-i-sumy-w-turcji-lawrow-spotka-sie-z-kuleba-ukraina-dzien-15-na-zywo',
    14 => 'usa-wysylaja-do-polski-rakiety-patriot-onz-juz-1207-ofiar-cywilnych-wojny-ukraina-dzien-14-na-zywo',
    13 => 'wojna-ukraina-dzien-13-na-zywo',
    12 => 'gina-dzieci-dramat-irpienia-biden-chce-zakazac-importu-ropy-z-rosji-dzien-12-na-zywo',
    11 => 'mariupol-ktory-znalismy-juz-nie-istnieje-mowi-mer-miasta-dzien-11-na-zywo',
    10 => 'mariupol-oblezony-zelenski-nato-daje-zielone-swiatlo-dla-bombardowan-dzien-10-na-zywo',
    9 => 'pozar-w-elektrowni-jadrowej-po-rosyjskim-ostrzale-kolejny-dzien-walk-w-ukrainie-dzien-9-na-zywo',
    8 => 'rosjanie-przejeli-cherson-potezne-eksplozje-w-kijowie-dzien-8-na-zywo',
    7 => 'kijow-charkow-i-cherson-pod-ostrzalem-w-przemyslu-prawicowe-bojowki-dzien-7-na-zywo',
    6 => 'dotknieta-sankcjami-rosja-z-zawzietoscia-bombarduje-miasta-na-ukrainie-dzien-6-na-zywo',
    5 => 'kijow-i-charkow-pod-kontrola-ukraincow-wartosc-rubla-spadla-o-40-proc-dzien-5-na-zywo',
    4 => 'kijow-i-charkow-sie-bronia-swift-przygotowuje-sie-do-wdrozenia-sankcji-dzien-4-na-zywo',
    3 => 'kijow-sie-broni-dzien-3-na-zywo',
    2 => 'kijow-stolica-ukrainy-pod-rosyjskim-ostrzalem-rakietowym-dzien-2-na-zywo',
    1 => 'rosja-zaatakowala-wojna-w-europie-stala-sie-faktem',
];
